#!/usr/bin/env bash
# Write the production .env (default ~/.local/share/holt-prod/.env; outside
# the repo so removing a worktree can never delete it). Every secret is
# generated fresh: nothing is shared with staging.
#
# Keeps an existing file unless --force. Rotating HOLT_SECRET_KEY makes
# users' saved BYOK keys unreadable, rotating AUTH_SECRET signs everyone
# out, and HOLT_DB_PASSWORD is baked into the db volume on first start.
set -euo pipefail
STATE="${HOLT_PROD_HOME:-$HOME/.local/share/holt-prod}"
mkdir -p "$STATE"
if [[ -f "$STATE/.env" && "${1:-}" != "--force" ]]; then
    echo "$STATE/.env exists; leaving it (pass --force to regenerate)"; exit 0
fi
rand() { python3 -c "import os,base64;print(base64.b64encode(os.urandom(32)).decode())"; }
hex() { python3 -c "import secrets;print(secrets.token_hex(24))"; }
umask 077
cat > "$STATE/.env" <<ENV
# Holt production. Generated by make-env.sh on $(date -u +%FT%TZ). Never commit.
# OAuth ids, OPENROUTER_API_KEY and GITHUB_TOKENS come from
# ~/.config/holt/secrets.env at deploy time (deploy.sh maps them), so they
# are not here. Without a secrets file, GITHUB_TOKENS falls back to
# \`gh auth token\`.
HOLT_ENV=production
HOLT_PROD_PORT=${HOLT_PROD_PORT:-8310}
HOLT_INTERNAL_KEY=$(hex)
HOLT_SECRET_KEY=$(rand)
AUTH_SECRET=$(rand)
HOLT_DB_PASSWORD=$(hex)
HOLT_JOB_CONCURRENCY=1
HOLT_STARTER_CACHE_HOURS=24
NEXT_PUBLIC_FREE_AI_QUOTA=3
ENV
echo "wrote $STATE/.env"
