"""Grow server/holt_server/seeds/repos.txt from public lists and GitHub search.

Free sources (downloaded as plain files, no GitHub API):
  - GSoC organisations, 2026 and 2023-2025: summerofcode.withgoogle.com's public
    org API. An org whose source link is a repository is taken as is; an org link
    is mapped to its main contribution repos by hand (GSOC_ORG_REPOS below); CNCF
    is mapped to its graduated, incubating and sandbox projects from
    cncf/landscape's landscape.yml. Orgs not on GitHub (or only mirrored there)
    are skipped.
  - LFX Mentorship: the public project API's repository links, for projects
    created since PROGRAMME_SINCE.
  - Outreachy: the communities named on the public alums pages since
    PROGRAMME_SINCE, mapped to their repos by hand (OUTREACHY_REPOS). Only the
    community names are read.
  - awesome-for-beginners (MunGell/awesome-for-beginners, README.md).
  - up-for-grabs (up-for-grabs/up-for-grabs.net, _data/projects/*.yml). Projects
    whose label stats were last updated before UFG_ACTIVE_SINCE are dropped.
  - goodfirstissue.dev (deepsourcelabs/good-first-issue, data/repositories.toml).

With `--check` (reads GITHUB_TOKEN; GraphQL, about 1 point per request):
  - Repository search, 100 results per point: per language in LANGUAGES, repos
    with open good-first-issue and help-wanted issues (LANGUAGE_TERMS); the topics
    maintainers use to invite newcomers (BEGINNER_TOPICS); repos in any language
    with open good-first-issue issues (ANY_LANGUAGE_TERMS); then the
    `hacktoberfest` topic, most-starred first, until the list reaches `--target`.
    All only take repos pushed in the last SEARCH_PUSHED_DAYS days. A search
    returns at most 1,000 results, so a longer one is cut into star ranges.
  - A programme org that links an organisation with no hand mapping is mapped to
    its ORG_TOP most-starred repos.
  - One batched pass (100 repos per query) drops repos that are gone, archived,
    forks or mirrors, under MIN_STARS stars, not pushed since ACTIVE_SINCE, or
    closed to outside pull requests, and writes renamed repos under their
    current name.

Without `--check` it only prints what the free sources hold and writes nothing.

Everything above the GENERATED marker in repos.txt is kept verbatim; everything
below it is rebuilt. A repo already below the marker stays (production has its
report and refreshes it) unless it is gone, archived, a fork or mirror, or closed
to outside pull requests (ALWAYS_DROPPED): the star and push floors, the name and
description filters and a search no longer returning it only keep new repos out.
One the filters would drop is printed for a person to decide. Catalogues (awesome-*, *-list, book lists, registries),
contribution farms, practice repos and personal dotfiles are dropped by name, and
under `--check` also by what their description says (SKIP_DESCRIPTION), which is
how a mirror GitHub does not flag as one is caught too.

    GITHUB_TOKEN=$(gh auth token) uv run python scripts/build_seed_list.py --check \\
        [--target 10000] [--dry-run]
"""

from __future__ import annotations

import argparse
import functools
import html
import io
import json
import os
import re
import sys
import tarfile
import time
import tomllib
import urllib.error
import urllib.request
from collections import Counter
from collections.abc import Iterator
from datetime import UTC, datetime, timedelta
from pathlib import Path

SEEDS = Path(__file__).resolve().parents[1] / "server" / "holt_server" / "seeds" / "repos.txt"
MARKER = "# ---- generated by scripts/build_seed_list.py; edit above this line ----"

GSOC_URL = "https://summerofcode.withgoogle.com/api/program/{year}/organizations/"
GSOC_PAST_YEARS = (2025, 2024, 2023)
LFX_URL = ("https://api.mentorship.lfx.linuxfoundation.org/projects/cache/paginate"
           "?from={start}&size=100&sortby=name&order=asc")
OUTREACHY_URL = "https://www.outreachy.org/alums/"
AFB_URL = "https://raw.githubusercontent.com/MunGell/awesome-for-beginners/main/README.md"
CNCF_URL = "https://raw.githubusercontent.com/cncf/landscape/master/landscape.yml"
UFG_URL = "https://codeload.github.com/up-for-grabs/up-for-grabs.net/tar.gz/refs/heads/gh-pages"
GFI_URL = "https://raw.githubusercontent.com/deepsourcelabs/good-first-issue/master/data/repositories.toml"

UFG_ACTIVE_SINCE = "2025-01-01"
PROGRAMME_SINCE = "2023"  # LFX projects and Outreachy rounds from this year on
ACTIVE_SINCE = "2026-06-01"  # no push since then: dormant
MIN_STARS = 20  # below this, a listed repo is almost always a personal project
ORG_TOP = 3  # repos taken from a programme org that has no hand mapping

LANGUAGES = ["Python", "JavaScript", "TypeScript", "Go", "Rust", "Java", "C++", "C#", "PHP",
             "Ruby", "Kotlin", "Swift", "Dart"]
LANGUAGE_TERMS = "good-first-issues:>=3 help-wanted-issues:>=1"
LANGUAGE_MIN_STARS = 50
BEGINNER_TOPICS = ["good-first-issue", "help-wanted", "first-timers-only", "beginner-friendly",
                   "up-for-grabs", "contributions-welcome"]
ANY_LANGUAGE_TERMS = "good-first-issues:>=3"
HACKTOBERFEST_TERMS = "topic:hacktoberfest"
SEARCH_PUSHED_DAYS = 60
REPO_FIELDS = ("nameWithOwner description isArchived isFork isMirror pushedAt stargazerCount "
               "hasPullRequestsEnabled pullRequestCreationPolicy")

# GSoC 2026 orgs whose source link is an org (or an umbrella/idea page), mapped to
# the repos where contributors actually open pull requests.
GSOC_ORG_REPOS: dict[str, list[str]] = {
    "aboutcode-org": ["aboutcode-org/scancode-toolkit", "aboutcode-org/vulnerablecode",
                      "aboutcode-org/scancode.io"],
    "accordproject": ["accordproject/concerto", "accordproject/template-playground"],
    "AOSSIE-Org": ["AOSSIE-Org/PictoPy"],
    "apache": ["apache/airflow", "apache/superset", "apache/beam", "apache/datafusion",
               "apache/iceberg"],
    "ArduPilot": ["ArduPilot/ardupilot", "ArduPilot/MissionPlanner"],
    "c2siorg": ["c2siorg/Webiu"],
    "Catrobat": ["Catrobat/Catroid", "Catrobat/Paintroid"],
    "cBioPortal": ["cBioPortal/cbioportal", "cBioPortal/cbioportal-frontend"],
    "CCExtractor": ["CCExtractor/ccextractor"],
    "ceph": ["ceph/ceph"],
    "checkstyle": ["checkstyle/checkstyle"],
    "circuitverse": ["CircuitVerse/CircuitVerse", "CircuitVerse/cv-frontend-vue"],
    "dart-lang": ["dart-lang/site-www", "dart-lang/pub-dev"],
    "dbpedia": ["dbpedia/extraction-framework"],
    "dlang": ["dlang/dmd", "dlang/phobos"],
    "dora-rs": ["dora-rs/dora"],
    "Ensembl": ["Ensembl/ensembl-vep"],
    "fortran-lang": ["fortran-lang/stdlib", "fortran-lang/fpm", "lfortran/lfortran"],
    "fossasia": ["fossasia/eventyay", "fossasia/badgemagic-app", "fossasia/pslab-app"],
    "GeomScale": ["GeomScale/volesti"],
    "haskell": ["haskell/cabal", "haskell/haskell-language-server"],
    "HSF": ["root-project/root"],
    "internetarchive": ["internetarchive/openlibrary"],
    "jderobot": ["JdeRobot/RoboticsAcademy"],
    "jenkinsci": ["jenkinsci/jenkins"],
    "jitsi": ["jitsi/jitsi-meet"],
    "json-schema-org": ["json-schema-org/website", "json-schema-org/json-schema-spec"],
    "kubeflow": ["kubeflow/pipelines", "kubeflow/trainer"],
    "kubevirt": ["kubevirt/kubevirt"],
    "learning-unlimited": ["learning-unlimited/ESP-Website"],
    "malariagen": ["malariagen/malariagen-data-python"],
    "meshery": ["meshery/meshery"],
    "metabrainz": ["metabrainz/musicbrainz-server", "metabrainz/listenbrainz-server",
                   "metabrainz/picard"],
    "metacall": ["metacall/core"],
    "mofa-org": ["mofa-org/mofa"],
    "neuroinformatics-unit": ["neuroinformatics-unit/movement"],
    "neutralinojs": ["neutralinojs/neutralinojs"],
    "ohcnetwork": ["ohcnetwork/care_fe", "ohcnetwork/care"],
    "omegaup": ["omegaup/omegaup"],
    "onebusaway": ["OneBusAway/onebusaway-android"],
    "openfoodfacts": ["openfoodfacts/openfoodfacts-server", "openfoodfacts/smooth-app",
                      "openfoodfacts/robotoff"],
    "openmf": ["openMF/web-app", "openMF/mifos-mobile", "openMF/android-client"],
    "openmrs": ["openmrs/openmrs-core", "openmrs/openmrs-esm-patient-chart"],
    "openrobotics": ["gazebosim/gz-sim", "ros2/ros2_documentation"],
    "openstreetmap": ["openstreetmap/openstreetmap-website", "openstreetmap/iD"],
    "openSUSE": ["openSUSE/open-build-service"],
    "openvinotoolkit": ["openvinotoolkit/openvino"],
    "openwisp": ["openwisp/openwisp-controller"],
    "OSGeo": ["OSGeo/gdal", "OSGeo/grass", "qgis/QGIS"],
    "owasp": ["OWASP/Nettacker", "zaproxy/zaproxy", "juice-shop/juice-shop"],
    "p4lang": ["p4lang/p4c"],
    "precice": ["precice/precice"],
    "processing": ["processing/p5.js", "processing/processing4"],
    "rizinorg": ["rizinorg/rizin", "rizinorg/cutter"],
    "ruby": ["ruby/ruby"],
    "scummvm": ["scummvm/scummvm"],
    "search": ["mandiant/capa", "mandiant/flare-floss"],  # FLARE links a topic search
    "stjude-rust-labs": ["stjude-rust-labs/sprocket"],
    "Submitty": ["Submitty/Submitty"],
    "sugarlabs": ["sugarlabs/musicblocks", "sugarlabs/sugar"],
    "tardis-sn": ["tardis-sn/tardis"],
    "typelevel": ["typelevel/cats", "typelevel/cats-effect"],
    "unikraft": ["unikraft/unikraft"],
    "webpack": ["webpack/webpack", "webpack/webpack.js.org"],
    "kiwix": ["kiwix/kiwix-android", "kiwix/kiwix-js"],
    # Umbrellas whose link is an idea page, not a repository.
    "numfocus/gsoc": ["numpy/numpy", "pandas-dev/pandas", "matplotlib/matplotlib",
                      "scipy/scipy", "jupyterlab/jupyterlab"],
}
# Non-GitHub source links whose projects do take pull requests on GitHub.
GSOC_OFF_GITHUB: dict[str, list[str]] = {
    "python-gsoc.org": ["python/cpython"],
    "openastronomy.org": ["astropy/astropy", "sunpy/sunpy"],
}

# Catalogues and farms, by name. The engine labels catalogues anyway; warming them
# wastes points.
SKIP_NAME = re.compile(
    r"(^|[-_.])(awesome|list|lists|books?|resources|roadmaps?|cheatsheets?|"
    r"interview|curated|collection|algorithms?|snippets?|practice)([-_.]|$)|^awesome|awesome$|"
    r"first[-_]?contributions?|hacktoberfest|add[-_]?your[-_]?name|contributors?[-_]list|"
    r"(^|[-_.])(dotfiles|hackerrank|beginners?)([-_.]|$)|leetcode[-_]solutions|\d+[-_]?days?[-_]?of|"
    r"^is-a-dev$|^register$|^public-apis$|^free-programming-books",
    re.I,
)
SKIP_REPOS = {
    "freecodecamp/freecodecamp",  # a curriculum site, kept only if already seeded
    "is-a-dev/register", "open-domains/register", "js-org/js.org",
    "ossu/computer-science", "trekhleb/javascript-algorithms", "thealgorithms/python",
    "thealgorithms/java", "thealgorithms/javascript", "thealgorithms/c-plus-plus",
    "thealgorithms/c", "thealgorithms/go", "thealgorithms/rust", "thealgorithms/c-sharp",
    "kamranahmedse/developer-roadmap", "ebookfoundation/free-programming-books",
    "theodinproject/curriculum", "magicianred/learn-by-doing", "eskayml/turtle-projects",
    "gimseng/99-ml-learning-projects", "meilynbear/beginnersmakelistpractice",
    "danthareja/contribute-to-open-source", "larymak/python-project-scripts",
    "codingchallengesfyi/sharedsolutions", "farhanashrafdev/90daysofcybersecurity",
    "swisskyrepo/payloadsallthethings", "projectdiscovery/public-bugbounty-programs",
    "kkrypt0nn/wordlists", "serhii-londar/open-source-mac-os-apps",
    "tomalaforge/angular-challenges",
    "timonwa/techroadmap", "buzzpy/dev-encyclopedia", "mason-org/mason-registry",
    "josharsh/100linesofcode", "zero-to-mastery/animation-nation",
    "opensource-communities/guestbook", "shamilahmdt/devtasks", "abhisheks008/dl-simplified",
    "dereknguyen269/programing-best-practices", "infosec-community/apac-conferences",
    "dotaiz/ai-ml", "bowbahdoe/modernjava", "sumn2u/learn-javascript",
    "pavanmudigonda/zero-to-ai", "dr-mushtaq/machine-learning",
    "wingkwong/leetcode-the-hard-way", "devvsakib/frontend-projects", "codedex-io/projects",
    "jentic/jentic-public-apis", "daviddavo/jgmd", "hanishrao/collective-ai-tools",
}
# What a description says when the name does not: the search sources reach lists,
# teaching material and practice repos that the hand-kept lists never named.
SKIP_MIRROR = re.compile(
    r"\[mirror\b|\bmirror(ed)? (of|from)\b|read-only mirror|github mirror|is a mirror\b", re.I)
SKIP_DESCRIPTION = re.compile(
    r"^\W*(\w+ - )?((a|an|the|community|largest|complete|comprehensive) )*"
    r"(curated (list|collection)|list) of\b|awesome list|"
    r"collection of (all )?(free|learning|devops|accessible)|free resources|cheat ?sheets?|"
    r"\b(book|tutorial|course|guide) for (\w+ )?beginners|\bbeginner'?s?'? (book|tutorial|guide)\b|"
    r"beginner[- ]friendly (projects|guide|git tutorial|roblox)|projects? for beginners|"
    r"\b\d+[- ]days? (of|challenge)|first (github )?pull request|"
    r"learn open[- ]source contributions|^personal portfolio|零基础|量化交易入门",
    re.I,
)

# Outreachy names communities, not repositories. Communities that work off GitHub
# (Debian, GNOME, Wikimedia, the kernel, ...) are left out.
OUTREACHY_REPOS: dict[str, list[str]] = {
    "Bioconductor": ["waldronlab/BugSigDBcuration"],
    "Bokeh": ["bokeh/bokeh"],
    "CNCF OpenTelemetry": ["open-telemetry/opentelemetry-collector-contrib",
                           "open-telemetry/opentelemetry.io"],
    "Ceph": ["ceph/ceph"],
    "ChRIS Project": ["FNNDSC/ChRIS_ui", "FNNDSC/ChRIS_ultron_backEnd"],
    "Creative Commons": ["creativecommons"],
    "Ersilia Open Source Initiative": ["ersilia-os/ersilia"],
    "Fedora": ["fedora-infra/bodhi"],
    "Firefox": ["mozilla/pdf.js", "mozilla-mobile/firefox-ios"],
    "Humanitarian OpenStreetMap Team": ["hotosm/tasking-manager", "hotosm/field-tm"],
    "KernelCI": ["kernelci/kernelci-core"],
    "LLVM": ["llvm/llvm-project"],
    "MDAnalysis": ["MDAnalysis/mdanalysis"],
    "Metal3": ["metal3-io/baremetal-operator"],
    "ModECI": ["ModECI/MDF"],
    "NetworkX": ["networkx/networkx"],
    "NixOS": ["NixOS/nixpkgs"],
    "OCaml": ["ocaml/ocaml", "ocaml/dune", "ocaml/opam"],
    "ODK-X": ["odk-x/services"],
    "Open Information Security Foundation": ["OISF/suricata"],
    "OpenRefine": ["OpenRefine/OpenRefine"],
    "Oppia": ["oppia/oppia", "oppia/oppia-android"],
    "Palisadoes Foundation": ["PalisadoesFoundation"],
    "Parsl": ["Parsl/parsl"],
    "Perl & Raku": ["Perl/perl5", "rakudo/rakudo"],
    "Servo": ["servo/servo"],
    "Unstructured Studio": ["unstructuredstudio/zubhub"],
    "Ushahidi": ["ushahidi/platform", "ushahidi/platform-client-mzima"],
    "Wagtail": ["wagtail/wagtail"],
    "caMicroscope": ["camicroscope/caMicroscope"],
    "moja global": ["moja-global/FLINT"],
    "scikit-image": ["scikit-image/scikit-image"],
    "systemd": ["systemd/systemd"],
    "xarray": ["pydata/xarray"],
}

GH_REPO = re.compile(r"github\.com/([A-Za-z0-9-]+)/([A-Za-z0-9_.-]+)")
GH_PAGES = {"orgs", "search", "topics", "sponsors", "apps", "marketplace"}


def get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": "holt-seed-builder"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read()


def repo_from(url: str) -> str | None:
    m = GH_REPO.search(url)
    if not m:
        return None
    owner, name = m.group(1), m.group(2).removesuffix(".git")
    if owner.lower() in GH_PAGES:
        return None
    return f"{owner}/{name}"


def github_parts(url: str) -> list[str]:
    path = url.split("github.com/", 1)[1].split("#")[0].split("?")[0]
    parts = [p for p in path.split("/") if p]
    return parts[1:2] if parts[:1] == ["orgs"] else parts


# The programme sources return `owner/repo`, or a bare `owner` for an organisation
# link that has no hand mapping (expanded by top_repos under --check).

@functools.cache
def cncf() -> list[str]:
    import yaml  # installed with the server's dependencies

    out = []
    for cat in yaml.safe_load(get(CNCF_URL))["landscape"]:
        for sub in cat.get("subcategories") or []:
            for item in sub.get("items") or []:
                if item.get("project") in {"graduated", "incubating", "sandbox"}:
                    if r := repo_from(item.get("repo_url") or ""):
                        out.append(r)
    return out


def gsoc(year: int) -> list[str]:
    out: list[str] = []
    umbrella = {k.lower(): v for k, v in GSOC_ORG_REPOS.items()}
    for org in json.loads(get(GSOC_URL.format(year=year))):
        url = (org["source_code"] or "").rstrip("/")
        if "github.com/" not in url:
            host = url.split("/")[2] if "//" in url else url
            out += GSOC_OFF_GITHUB.get(host, [])
            continue
        parts = github_parts(url)
        if not parts:
            continue
        key = "/".join(parts[:2]).lower() if len(parts) >= 2 else parts[0].lower()
        if key == "cncf":
            out += cncf()
        elif key in umbrella:
            out += umbrella[key]
        elif parts[0].lower() in umbrella:
            if len(parts) == 1 or parts[0] == "search":
                out += umbrella[parts[0].lower()]
            elif parts[1] not in {".github", "ProjectIdeas", "GSoC", "gsoc"}:
                out.append(f"{parts[0]}/{parts[1]}")
        elif parts[0] in GH_PAGES:
            continue
        elif len(parts) == 1 or parts[1] in {".github", "ProjectIdeas", "GSoC", "gsoc"}:
            out.append(parts[0])
        else:
            out.append(f"{parts[0]}/{parts[1]}")
    return out


def lfx() -> list[str]:
    out: list[str] = []
    start = 0
    while hits := json.loads(get(LFX_URL.format(start=start)))["hits"]["hits"]:
        for hit in hits:
            project = hit["_source"]
            url = (project.get("repoLink") or "").strip()
            if (project.get("createdOn") or "") < PROGRAMME_SINCE or "github.com/" not in url:
                continue
            parts = github_parts(url)
            if parts and parts[0] not in GH_PAGES:
                out.append("/".join(parts[:2]).removesuffix(".git"))
        start += len(hits)
    return out


def outreachy() -> list[str]:
    out: list[str] = []
    unmapped: set[str] = set()
    index = get(OUTREACHY_URL).decode("utf-8")
    for rnd in sorted(set(re.findall(r'href="/alums/(\d{4}-\d{2})/"', index))):
        if rnd < PROGRAMME_SINCE:
            continue
        page = get(f"{OUTREACHY_URL}{rnd}/").decode("utf-8")
        for community in re.findall(r"<BR>\s*([^<>]+?) mentor\(s\):", page):
            name = html.unescape(community.strip())
            if name in OUTREACHY_REPOS:
                out += OUTREACHY_REPOS[name]
            else:
                unmapped.add(name)
    if unmapped:
        print("outreachy communities with no mapping: " + ", ".join(sorted(unmapped)),
              file=sys.stderr)
    return out


def afb() -> list[str]:
    text = get(AFB_URL).decode("utf-8")
    return [r for u in re.findall(r"\]\((https://github\.com/[^)\s]+)\)", text)
            if (r := repo_from(u))]


def ufg() -> list[str]:
    out = []
    with tarfile.open(fileobj=io.BytesIO(get(UFG_URL)), mode="r:gz") as tar:
        for member in tar:
            if "/_data/projects/" not in member.name or not member.name.endswith(".yml"):
                continue
            text = tar.extractfile(member).read().decode("utf-8", "replace")
            site = re.search(r"^site:\s*(\S+)", text, re.M)
            updated = re.search(r"last-updated:\s*'?\"?(\d{4}-\d{2}-\d{2})", text)
            if not site or not updated or updated.group(1) < UFG_ACTIVE_SINCE:
                continue
            if r := repo_from(site.group(1)):
                out.append(r)
    return out


def gfi() -> list[str]:
    data = tomllib.loads(get(GFI_URL).decode("utf-8"))
    return [r for u in data["repositories"] if (r := repo_from(u))]


def skipped(repo: str) -> bool:
    return repo.lower() in SKIP_REPOS or bool(SKIP_NAME.search(repo.split("/")[1]))


# The reasons that also remove a repo already in the list.
ALWAYS_DROPPED = {"gone", "archived", "fork or mirror", "closed to outside pull requests"}
BY_DESCRIPTION = {"a mirror by its description", "catalogue or farm"}


def drop_reason(node: dict | None) -> str | None:
    """Why a repository (REPO_FIELDS) does not belong in the list, or None if it does."""
    if not node:
        return "gone"
    if node["isArchived"]:
        return "archived"
    if node["isFork"] or node.get("isMirror"):
        return "fork or mirror"
    if (node.get("hasPullRequestsEnabled") is False
            or node.get("pullRequestCreationPolicy") == "COLLABORATORS_ONLY"):
        return "closed to outside pull requests"
    description = node.get("description") or ""
    if SKIP_MIRROR.search(description):
        return "a mirror by its description"
    if SKIP_DESCRIPTION.search(description):
        return "catalogue or farm"
    if node["stargazerCount"] < MIN_STARS:
        return f"under {MIN_STARS} stars"
    if (node["pushedAt"] or "") < ACTIVE_SINCE:
        return f"no push since {ACTIVE_SINCE}"
    return None


class GitHub:
    """GraphQL with the points each query cost added up."""

    def __init__(self, token: str) -> None:
        self.token = token
        self.points = 0

    def graphql(self, query: str, variables: dict | None = None) -> dict:
        body = json.dumps({"query": query, "variables": variables or {}}).encode()
        for attempt in range(4):
            req = urllib.request.Request(
                "https://api.github.com/graphql", data=body,
                headers={"Authorization": f"bearer {self.token}",
                         "User-Agent": "holt-seed-builder"})
            try:
                with urllib.request.urlopen(req, timeout=120) as resp:
                    data = json.loads(resp.read()).get("data")
            except (urllib.error.URLError, TimeoutError):
                data = None
            if data:
                self.points += data["rateLimit"]["cost"]
                return data
            time.sleep(5 * (attempt + 1))
        sys.exit("GitHub GraphQL kept failing; nothing written")


def search(gh: GitHub, terms: str, min_stars: int) -> Iterator[dict]:
    """Repositories matching `terms`, most-starred first. A search returns at most
    1,000 results, so a longer one continues in the star range below the last result."""
    query = ("query($q: String!, $after: String) { rateLimit { cost } "
             "search(type: REPOSITORY, query: $q, first: 100, after: $after) { repositoryCount "
             f"pageInfo {{ hasNextPage endCursor }} nodes {{ ... on Repository {{ {REPO_FIELDS} }} }} }} }}")
    ceiling = None
    while True:
        stars = f"stars:>={min_stars}" if ceiling is None else f"stars:{min_stars}..{ceiling}"
        after, lowest = None, None
        while True:
            found = gh.graphql(query, {"q": f"{terms} {stars} sort:stars-desc", "after": after})["search"]
            for node in found["nodes"]:
                if node:
                    lowest = node["stargazerCount"]
                    yield node
            if not found["pageInfo"]["hasNextPage"]:
                break
            after = found["pageInfo"]["endCursor"]
        if found["repositoryCount"] <= 1000 or lowest is None:
            return
        ceiling = lowest if ceiling is None or lowest < ceiling else ceiling - 1
        if ceiling < min_stars:
            return


def top_repos(gh: GitHub, owners: list[str]) -> dict[str, list[str]]:
    """owner (lowercase) -> its ORG_TOP most-starred repositories that are its own."""
    out: dict[str, list[str]] = {}
    for i in range(0, len(owners), 50):
        chunk = owners[i:i + 50]
        body = " ".join(
            f"o{j}: repositoryOwner(login: {json.dumps(owner)}) {{ repositories(first: {ORG_TOP}, "
            "isFork: false, ownerAffiliations: OWNER, "
            "orderBy: {field: STARGAZERS, direction: DESC}) { nodes { nameWithOwner } } }"
            for j, owner in enumerate(chunk))
        data = gh.graphql(f"query {{ rateLimit {{ cost }} {body} }}")
        for j, owner in enumerate(chunk):
            nodes = (data.get(f"o{j}") or {}).get("repositories", {}).get("nodes") or []
            out[owner.lower()] = [n["nameWithOwner"] for n in nodes if n]
    return out


def check(gh: GitHub, repos: list[str]) -> dict[str, dict | None]:
    """repo -> its REPO_FIELDS, or None when it is gone."""
    result: dict[str, dict | None] = {}
    for i in range(0, len(repos), 100):
        chunk = repos[i:i + 100]
        body = " ".join(
            f'r{j}: repository(owner: {json.dumps(r.split("/")[0])}, '
            f'name: {json.dumps(r.split("/")[1])}) {{ {REPO_FIELDS} }}'
            for j, r in enumerate(chunk))
        data = gh.graphql(f"query {{ rateLimit {{ cost }} {body} }}")
        for j, r in enumerate(chunk):
            result[r] = data.get(f"r{j}")
    return result


def listed(text: str) -> set[str]:
    return {line.split("#", 1)[0].strip().lower() for line in text.splitlines()} - {""}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true",
                    help="use GitHub (GITHUB_TOKEN): search, org mapping, one batched hygiene pass")
    ap.add_argument("--target", type=int, default=10000,
                    help="with --check, fill the list to this many repos from the hacktoberfest topic")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    gh = None
    if args.check:
        if not os.environ.get("GITHUB_TOKEN"):
            sys.exit("--check needs GITHUB_TOKEN")
        gh = GitHub(os.environ["GITHUB_TOKEN"])

    text = SEEDS.read_text(encoding="utf-8")
    head, _, generated = text.partition(MARKER)
    head = head.rstrip("\n")
    earlier: dict[str, str] = {}
    topic_before: set[str] = set()  # the ones the hacktoberfest topic supplied
    block = ""
    for line in generated.splitlines():
        if line.startswith("# source: "):
            block = line.removeprefix("# source: ").split(" (")[0]
        elif r := line.split("#", 1)[0].strip():
            earlier[r.lower()] = r
            if block == "hacktoberfest-topic":
                topic_before.add(r.lower())
    before = set(earlier)
    seen = listed(head)
    kept = len(seen)
    dropped: Counter[str] = Counter()
    stayed: Counter[str] = Counter()  # already listed, kept for a reason that stops a new repo
    flagged: list[str] = []  # already listed, and the name or description filter matches
    known: dict[str, dict] = {}  # repos GitHub search already described
    pushed = (datetime.now(UTC) - timedelta(days=SEARCH_PUSHED_DAYS)).strftime("%Y-%m-%d")
    scope = f"pushed:>={pushed} archived:false fork:false"

    def searched(name: str, terms: str) -> tuple[str, str, list[str]]:
        terms = f"{terms} {scope}"
        nodes = list(search(gh, terms, LANGUAGE_MIN_STARS))
        known.update((n["nameWithOwner"], n) for n in nodes)
        return (name, f"GitHub search: {terms} stars:>={LANGUAGE_MIN_STARS}",
                [n["nameWithOwner"] for n in nodes])

    sources: list[tuple[str, str, list[str]]] = []
    if gh:
        sources += [searched(f"good-first-issues {language}",
                             f'language:"{language}" {LANGUAGE_TERMS}')
                    for language in LANGUAGES]
    past = ", ".join(str(y) for y in GSOC_PAST_YEARS)
    sources += [
        ("gsoc-2026", f"GSoC 2026 organisations ({GSOC_URL.format(year=2026)}), orgs mapped by hand",
         gsoc(2026)),
        ("gsoc-past", f"GSoC organisations {past} (same API)",
         [r for year in GSOC_PAST_YEARS for r in gsoc(year)]),
        ("lfx-mentorship", f"LFX Mentorship projects since {PROGRAMME_SINCE} ({LFX_URL.split('?')[0]})",
         lfx()),
        ("outreachy", f"Outreachy communities since {PROGRAMME_SINCE} ({OUTREACHY_URL}), mapped by hand",
         outreachy()),
        ("goodfirstissue.dev", GFI_URL, gfi()),
        ("awesome-for-beginners", AFB_URL, afb()),
        ("up-for-grabs", f"{UFG_URL} (label stats updated since {UFG_ACTIVE_SINCE})", ufg()),
    ]
    if gh:
        # After the lists above, so a repo they name stays in their block.
        sources += [searched(f"topic {topic}", f"topic:{topic}") for topic in BEGINNER_TOPICS]
        sources.append(searched("good-first-issues any language", ANY_LANGUAGE_TERMS))

    owners = sorted({r for _, _, found in sources for r in found if "/" not in r}, key=str.lower)
    mapped = top_repos(gh, owners) if gh else {}
    if owners and not gh:
        dropped["organisation link, not mapped without --check"] = len(owners)

    blocks: list[tuple[str, str, list[str]]] = []
    for name, where, found in sources:
        new = []
        for repo in (r for f in found for r in ([f] if "/" in f else mapped.get(f.lower(), []))):
            if repo.lower() in seen:
                dropped["duplicate"] += 1
            elif skipped(repo) and repo.lower() not in before:
                dropped["catalogue or farm"] += 1
                seen.add(repo.lower())
            else:
                seen.add(repo.lower())
                new.append(repo)
        blocks.append((name, where, new))
    unsourced = [repo for key, repo in earlier.items() if key not in seen]

    if gh:
        status = known | check(gh, [r for r in [*(r for _, _, b in blocks for r in b), *unsourced]
                                    if r not in known])
        seen = listed(head)

        def stays(repo: str) -> str | None:
            """The name to list `repo` under, or None when it is dropped."""
            why = drop_reason(status[repo])
            listed_before = repo.lower() in before
            if why and (why in ALWAYS_DROPPED or not listed_before):
                dropped[why] += 1
                return None
            current = status[repo]["nameWithOwner"]
            if current.lower() in seen:
                dropped["duplicate after rename"] += 1
                return None
            if listed_before:
                if why in BY_DESCRIPTION or skipped(repo):
                    why = "catalogue, farm or mirror by name or description"
                    flagged.append(current)
                if why:
                    stayed[why] += 1
            seen.add(current.lower())
            return current

        blocks = [(name, where, [current for repo in new if (current := stays(repo))])
                  for name, where, new in blocks]
        carried = {current.lower(): current for repo in unsourced
                   if (current := stays(repo))}
        seen -= set(carried)  # so the topic search below can put them back in its block

        # The hacktoberfest topic is far larger than the list: take it from the top.
        room = args.target - kept - sum(len(b) for _, _, b in blocks) - len(carried)
        terms = f"{HACKTOBERFEST_TERMS} {scope}"
        topic: list[str] = []
        floor = None
        for node in search(gh, terms, MIN_STARS) if room > 0 else ():
            repo = node["nameWithOwner"]
            if repo.lower() in seen:
                continue
            seen.add(repo.lower())
            if repo.lower() in carried:
                topic.append(carried.pop(repo.lower()))
            elif skipped(repo):
                dropped["catalogue or farm"] += 1
            elif why := drop_reason(node):
                dropped[why] += 1
            else:
                topic.append(repo)
                floor = node["stargazerCount"]
                room -= 1
                if room <= 0:
                    break
        # Below where the search stopped, the topic's earlier repos stay in its block.
        topic += [carried.pop(key) for key in list(carried) if key in topic_before]
        blocks.insert(0, ("hacktoberfest-topic",
                          f"GitHub search: {terms} stars:>={MIN_STARS}, most-starred first"
                          + (f" (reached {floor} stars)" if floor else ""), topic))
        stayed["no source returns it any more"] = len(carried)
        blocks.append(("earlier builds", "listed by an earlier build and returned by no source "
                       "now; kept while GitHub says they still take outside pull requests",
                       list(carried.values())))

    out = [head, "", MARKER]
    for name, where, new in blocks:
        out += ["", f"# source: {name} ({len(new)}) {where}"] + sorted(new, key=str.lower)
    total = kept + sum(len(b) for _, _, b in blocks)
    for name, _, new in blocks:
        print(f"{name}: {len(new)} new", file=sys.stderr)
    for why, n in dropped.most_common():
        print(f"dropped ({why}): {n}", file=sys.stderr)
    for why, n in stayed.most_common():
        print(f"already listed, kept ({why}): {n}", file=sys.stderr)
    if flagged:
        print("already listed, kept, but the name or description filter matches (remove by hand "
              "if they should go): " + ", ".join(sorted(flagged, key=str.lower)), file=sys.stderr)
    after = {r.lower() for _, _, b in blocks for r in b}
    print(f"no longer listed: {len(before - after)} of {len(before)} generated before",
          file=sys.stderr)
    if gh:
        print(f"GitHub points used: {gh.points}", file=sys.stderr)
    print(f"kept {kept} existing; total {total}", file=sys.stderr)
    if not gh:
        print("nothing written: the committed list is built with --check", file=sys.stderr)
    elif not args.dry_run:
        SEEDS.write_text("\n".join(out) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
